# Generated by Django 4.2.14 on 2024-07-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_remove_user_id_alter_user_user_id_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
